apiVersion: v1
kind: Namespace
metadata:
  name: mspr-us
  labels:
    name: mspr-us
    cluster: us
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: mspr-france
  labels:
    name: mspr-france
    cluster: france
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: mspr-switzerland
  labels:
    name: mspr-switzerland
    cluster: switzerland
    environment: production